#!/bin/bash
WATER_VAL=$(echo "$WATER" | tr water 01234) STIR_VAL=$(echo "$STIR" | tr stir. 01234) BESTCHOL=$(echo "obase=bestchol; $((5#$WATER_VAL + 5#$STIR_VAL))" | bc) echo "The sum of WATER and STIR is: $BESTCHOL"
